export default function ErrorThrow() {

  throw new Error('from ErrorThrow');

  return (
    <p>正しく実行されました。</p>
  );
}
